# https://docs.docker.com/compose/

version: "3.7"

volumes:
  database:

networks:
  awari:

services:
  database:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
    - awari
    volumes:
    - database:/var/lib/mysql:rw
  
  api:
    build:
      context: .
      target: build
    ports:
    - 4500:3000
    networks:
    - awari
    volumes:
    - .:/srv/app
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_HOST: database
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: root
      DATABASE_PASS: "123456"
      DATABASE_NAME: "blog"

  redis:
    image: redis:alpine
    networks:
    - awari
